### ISSUE TITLE
Problem when cloning org.cometd.Message

### ISSUE THREAD

**Issue by sbordet** [sbordet/import_issues#86]
Hi,

I've created an extension, and am cloning the message as recommended in the javadoc for org.cometd.Client:

http://jetty.codehaus.org/jetty/cometd/apidocs/org/cometd/Client.html#addExtension(org.cometd.Extension)

However, when I return the cloned message from the extension, I get the following issue:

```
2010-03-11 11:55:32.402:WARN::handle failed
java.lang.IllegalStateException: 7 => 9
	at org.eclipse.jetty.client.HttpExchange.setStatus(HttpExchange.java:309)
	at org.eclipse.jetty.client.HttpConnection.handle(HttpConnection.java:271)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:462)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:436)
	at java.lang.Thread.run(Thread.java:619)
```
I'm using cometd-java-client v1.0.1 and jetty-client v7.0.1.v20091125

Here's the code:
```
@Override
public Message send(Client client, Message message) {
    final AccessControlContext ctx = AccessController.getContext();
    final Subject subject = Subject.getSubject(ctx);
		
    LOG.debug("Adding " + subject + " to " + message);

    final Message clonedMessage = (Message) message.clone();
		
    return clonedMessage;
}
```

**Comment by sbordet** [comment]
Originally reported by grantd on 2010-03-11 07:01:34.0

**Comment by sbordet** [comment]
grantd on 2010-03-24 03:39:24.0:
Removed irrelevant line.

**Comment by sbordet** [comment]
sbordet on 2010-03-26 08:36:39.0:
Actually the line you removed made a sense, because otherwise there is no reason to clone the message (since it is not modified). But we got the point :)

This issue uncovered a design issue that it is fixed in CometD 2, but won't be addressed in CometD 1.
Short story, do not clone messages; if you need to, create a new one and deep copy it. Long story below.

The stack trace reported above shows the problem on the client. However, messages sent from clients do not get sent to multiple clients, but only to the server. So basically in a client-side extension, it makes no sense to clone or deep copy messages. Just modify the message you get passed, and that's it.

On server side things change. There are 2 kinds of server-side extensions: per-Bayeux extensions (that apply to all server-side Client objects) - for example the `TimestampExtension` - and per-Client extension (that apply to a single server-side Client object) - for example the `AcknowledgedMessagesClientExtension`.
Per-Bayeux extensions do not need message cloning or deep copying, because of their nature: they apply to all server-side Client objects.
Per-Client extensions may need message cloning or deep copying, where one wants to send a message on a channel, but the message needs modifications for some of the subscribers of the channel.

Your example of using `Subject.getSubject()` above is most appropriate: you may want to detect if a user has a "gold" account, and add extra information on the message for that user, but you don't want the extra information to be delivered to non-gold account users. But should be done on a server-side, per-Client extension.

So, cloning or deep copying a message does have a use case, but unfortunately `Object.clone()` is so horribly broken in Java, that it is impossible to use it, and it was a mistake to make it surface in the `org.cometd.Message` interface.

`org.cometd.Message.clone()` will be deprecated and users are encouraged to create a new message, recursively deep copy it, paying attention to what other extensions may have added, then modify it and return it.
To recursively deep copy a message, a quick solution is to convert it to a JSON string and then back to a `Message`, and this can be done using `AbstractBayeux.getMsgJSON().toJSON()` and `AbstractBayeux.getMsgJSON().fromJSON()` methods.
See also this test: http://svn.cometd.org/trunk/cometd-java/client/src/test/java/org/cometd/client/MessageDeepCopyTest.java, which shows how it is possible to implement the use case.
I would like to stress that deep copying messages is only useful in server-side, per-Client extensions.

I will close the bug as "Wont Fix" in the sense that `Message.clone()` won't be fixed to support deep cloning, but the solution is available by other means, as the test case shows.
