### ISSUE TITLE
NullPointerException running in Glassfish without ContinuationFilter faux=true

### ISSUE THREAD

**Issue by sbordet** [sbordet/import_issues#89]
Building the latest cometd HEAD and deploying on Glassfish results in a NullPointerException in Servlet3Continuation.setTimeout() because _context is null.  This may actually be a problem in Jetty, I'm not sure.

I'm trying hard to give you 'steps to reproduce' but I have trouble installing the cometd war's to glassfish, because a web.xml contains 'DUMMY web.xml' and fails to parse during deployment.  I hope you can take these partial steps and make sense of your own war files, because I think you're far better at me at understanding your build system.

- fetch cometd trunk "svn co http://svn.cometd.com/trunk  cometd/trunk"

- build for jetty7 dojo configuration "cd cometd/trunk ; mvn archetype:generate -DarchetypeCatalog=http://cometd.org"

- install glassfish with default settings (but disable the Update Tool).  Download from http://download.java.net/glassfish/v3/promoted/, e.g. http://download.java.net/glassfish/v3/promoted/glassfish-v3-b74b-unix.sh, install to /opt/glassfish-v4-b74b using "sh ./<install.sh>".  Make sure current user has write prive to destination, of course.  Make sure other apps on port 8080 are stopped before running installer.

- after install, glassfish will not yet be running.

- copy required cometd and jetty jars to the lib directory:

cp cometd-java/server/target/cometd-java-server-1.0.2-SNAPSHOT.jar /opt/glassfish-v3-b74b-cometd/glassfish/domains/domain1/lib
cp cometd-java/api/target/cometd-api-1.0.2-SNAPSHOT.jar /opt/glassfish-v3-b74b-cometd/glassfish/domains/domain1/lib

cp cometd-java/examples/target/cometd-examples-java-1.0.2-SNAPSHOT/WEB-INF/lib/jetty-* /opt/glassfish-v3-b74b-cometd/glassfish/domains/domain1/lib

- start the glassfish server

cd /opt/glassfish-v3-b74b-cometd/bin
./asadmin start-domain

- deploy the javascript demo (3 wars) from a trunk build to the autodeploy directory:

cp cometd-javascript/common/target/cometd-javascript-common-1.0.2-SNAPSHOT.war cometd-javascript/dojo/target/cometd-javascript-dojo-1.0.2-SNAPSHOT.war cometd-javascript/examples-dojo/target/cometd-examples-dojo-1.0.2-SNAPSHOT.war /opt/glassfish-v3-b74b-cometd/glassfish/domains/domain1/autodeploy/

- At this point, deployment fails, see SAXParseException in glassfish/domains/domain1/logs/server.xml.

In my own app, running cometd javascript client and java jars and jetty components as above, we would like to run with a 'plain' ContinuationCometdServlet.  Running with latest trunk results in the following stack trace:

WARNING: StandardWrapperValve[cometd]: PWC1406: Servlet.service() for
servlet cometd threw exception
java.lang.NullPointerException
        at
org.eclipse.jetty.continuation.Servlet3Continuation.setTimeout(Servlet3Continuation.java:
139)
        at
org.cometd.server.continuation.ContinuationCometdServlet.service(ContinuationCometdServlet.java:
201)
        at
org.cometd.server.AbstractCometdServlet.service(AbstractCometdServlet.java:
258)
        at
org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:
1523)

It seems that nothing has initialised the AsyncContext _context in Servlet3Continuation.java.

The feeling I continually get from Cometd developers is that you don't "do" Glassfish and so cannot debug.  This problem is beyond my abilities because I don't understand the AsyncContext or real workings of Continuations.  Is there anything else I can do to help here?

**Comment by sbordet** [comment]
Originally reported by neekfenwick on 2010-03-21 23:29:02.0

**Comment by sbordet** [comment]
neekfenwick on 2010-03-28 00:46:31.0:
I've made a very simple web project using netbeans that demonstrates the problem.  The build.xml doesn't rely on any NetBeans stuff (though there is the usual netbeans build/deploy stuff in the nbproject/build-impl.xml, ignore that).  The client program is a almost 100% copy of the simple app on the cometd.org Primer page. it simply connects to the cometd servlet.

1/ install glassfish as before
2/ unpack the CometTest project I'll attach
3/ unpack a dojo-1.4.2-src release into CometTest project root dir (not included here because it's huge)
4/ check paths in CometTest/build.xml .. it presumes you have a cometd.org trunk checked out and built for dojo-jetty7 as described earlier in this bug report.  also needs to know where your glassfish is installed.
5/ run 'ant build-war'

It should
- take the javascript client from the cometd.org trunk and overwrite what's in the dojo src release
- run a dojo build, taking the dojo release from CometTest/dojo-release-1.4.2-src and building it into web/resource/dojo for inclusion in the CometTest.war.  It uses CometTest.profile.js which simply states it will use the dojox.cometd namespace.
- take the cometd java jars (cometd api, java server) and copy to CometTest's lib dir, for inclusion in CometTest.war
- take the jetty jars (jetty util, jetty continuations) and copy to the glassfish default domain's lib dir. (for some reason, putting them in the war means the cometd servlet doesn't start)
- build a CometTest.war containing web.xml referencing cometd servlet, dojo, and simple index.jsp

You should get a CometTest.war file ready for deployment.

1/ start glassfish (cd glassfish-dir/bin ; ./asadmin start-domain)
2/ copy CometTest.war into glassfish-dir/glassfish/domains/domain1/autodeploy

glassfish-dir/glassfish/domains/domain1/log/server.log should show it has been deployed.

Visit http://your-server:8080/CometTest/index.jsp.

It should load dojo.js and comettest.js (with comet javascript client build in), handshake ok, initial connect ok, but second connect fail.  Server log shows:

[#|2010-03-28T11:32:27.851+0700|WARNING|glassfishv3.0|javax.enterprise.system.container.web.com.sun.enterprise.web|_ThreadID=24;_ThreadName=http-thread-pool-8080-(2);|StandardWrapperValve[cometd]: PWC1406: Servlet.service() for servlet cometd threw exception
java.lang.NullPointerException
        at org.eclipse.jetty.continuation.Servlet3Continuation.setTimeout(Servlet3Continuation.java:139)
        at org.cometd.server.continuation.ContinuationCometdServlet.service(ContinuationCometdServlet.java:201)
        at org.cometd.server.AbstractCometdServlet.service(AbstractCometdServlet.java:258)
        at org.apache.catalina.core.StandardWrapper.service(StandardWrapper.java:1523)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:279)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:188)
        at org.apache.catalina.core.StandardPipeline.invoke(StandardPipeline.java:641)
        at com.sun.enterprise.web.WebPipeline.invoke(WebPipeline.java:97)
        at com.sun.enterprise.web.PESessionLockingStandardPipeline.invoke(PESessionLockingStandardPipeline.java:85)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:185)
        at org.apache.catalina.connector.CoyoteAdapter.doService(CoyoteAdapter.java:332)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:233)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:165)
        at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:791)
        at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:693)
        at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:954)
        at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:170)
        at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:135)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:102)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:88)
        at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:76)
        at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:53)
        at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:57)
        at com.sun.grizzly.ContextTask.run(ContextTask.java:69)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:330)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:309)
        at java.lang.Thread.run(Thread.java:619)
|#]

**Comment by sbordet** [comment]
neekfenwick on 2010-03-28 00:50:02.0:
CometTest web project, not including cometd.org checkout, or dojo source.

**Comment by sbordet** [comment]
neekfenwick on 2010-03-29 02:58:34.0:
By the way, this issue was previously mentioned in this thread on cometd-users: http://groups.google.com/group/cometd-users/browse_thread/thread/53ae472974378826/86120f5860f35b75#86120f5860f35b75

**Comment by sbordet** [comment]
gregw on 2010-03-29 05:25:16.0:
I believe this issue will be dealt with as the changes from jetty continuations 7.0.2 filter through into the next release of cometd.

ie hopefully fixed this week.

**Comment by sbordet** [comment]
gregw on 2010-04-13 07:39:03.0:
There was an issue in Jetty continuations, that was fixed with the 7.0.2 release.

However, there is a glassfish bug that prevents continuations working in the non-faux mode.
I have raised:
   https://glassfish.dev.java.net/issues/show_bug.cgi?id=11739

I'll leave this issue open so that we can track their resolution of the problem.

**Comment by sbordet** [comment]
sbordet on 2011-09-09 04:17:01.0:
The GlassFish bug was fixed a while ago, closing this bug.
